### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by captainrdubb** [hanayashiki/es_resolve#1]
Thank you for this great library. It's really helpful. Would it be possible to add more detail to the documentation. Specifically, I'm having trouble understanding the purpose for each resolver option. I think that one of the options will help me. https://github.com/hanayashiki/es_resolve/blob/main/src/es_resolver.rs#L32

**Comment by hanayashiki** [comment]
Hi, can you check if the latest documentation makes sense a little bit?

https://github.com/hanayashiki/es_resolve/blob/b1ae2467a07648f11e2532def20892cb51f63115/src/types.rs#L21
